/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinalp2_carlosochoa;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import javax.swing.JColorChooser;
import java.awt.Color;
import java.awt.Font;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Carlos Antonio
 */
public class ProyectoPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProyectoPrincipal.class.getName());

    File carpetaPrincipal = new File("ArchivosCacholaOS");
    File archivoAbierto = null;
    Usuario[] usuarios = new Usuario[20];
    int cantidadUsuarios = 0;
    int usuarioEditando = -1;
    Usuario usuarioActual = null;

    /**
     * Creates new form ProyectoPrincipal
     */
    public ProyectoPrincipal() {
        initComponents();
        setSize(1000, 650);
        setLocationRelativeTo(null);
        setResizable(false);

        usuarios[0] = new Usuario("admin", "1234", "Administrador");
        cantidadUsuarios = 1;

        pbLogin.setValue(0);
        pbLogin.setStringPainted(true);

        jpLogin.setVisible(true);
        jpInicio.setVisible(false);
        jpEditor.setVisible(false);
        jpExplorador.setVisible(false);
        jpUsuarios.setVisible(false);

        Timer timer = new Timer(1000, e -> {
            Date fechaActual = new Date();

            lblHora.setText(new SimpleDateFormat("hh:mm:ss a").format(fechaActual));
            lblFecha.setText(new SimpleDateFormat("dd/MM/yyyy").format(fechaActual));
        });

        timer.start();
        //Arbol

        if (!carpetaPrincipal.exists()) {
            carpetaPrincipal.mkdir();
        }

        new File(carpetaPrincipal, "Documentos").mkdir();
        new File(carpetaPrincipal, "Tareas").mkdir();
        new File(carpetaPrincipal, "Otros").mkdir();

        DefaultMutableTreeNode raiz
                = new DefaultMutableTreeNode("CacholaOS");

        cargarArchivos(carpetaPrincipal, raiz);

        DefaultTreeModel modeloArbol
                = new DefaultTreeModel(raiz);

        treeArchivos.setModel(modeloArbol);

        if (!carpetaPrincipal.exists()) {
            carpetaPrincipal.mkdir();
        }

        new File(carpetaPrincipal, "Documentos").mkdir();
        new File(carpetaPrincipal, "Tareas").mkdir();
        new File(carpetaPrincipal, "Otros").mkdir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupArchivos = new javax.swing.JPopupMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemRenombrar = new javax.swing.JMenuItem();
        itemEliminar = new javax.swing.JMenuItem();
        dialogUsuario = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioCRUD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrasenaCRUD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        btnGuardarUsuario = new javax.swing.JButton();
        btnCancelarUsuario = new javax.swing.JButton();
        jpContenedor = new javax.swing.JPanel();
        jpLogin = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        pbLogin = new javax.swing.JProgressBar();
        lblEstado = new javax.swing.JLabel();
        jpInicio = new javax.swing.JPanel();
        jpNavbar = new javax.swing.JPanel();
        lblNombreSistema = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPersonalizar = new javax.swing.JButton();
        lblUsuarioActual = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jpEscritorio = new javax.swing.JPanel();
        btnEditor = new javax.swing.JButton();
        btnExplorador = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jpEditor = new javax.swing.JPanel();
        lblTituloEditor = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnColorEditor = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEditor = new javax.swing.JTextArea();
        btnColorFuente = new javax.swing.JButton();
        lblFuenteEditor = new javax.swing.JLabel();
        jcbFuenteEditor = new javax.swing.JComboBox<>();
        lblTamanoEditor = new javax.swing.JLabel();
        jcbTamanoEditor = new javax.swing.JComboBox<>();
        btnBold = new javax.swing.JButton();
        btnItalics = new javax.swing.JButton();
        jpExplorador = new javax.swing.JPanel();
        lblExploradorTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeArchivos = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArchivos = new javax.swing.JTable();
        btnCrearArchivo = new javax.swing.JButton();
        btnCrearCarpeta = new javax.swing.JButton();
        btnEliminarArchivo = new javax.swing.JButton();
        btnVolverExplorador = new javax.swing.JButton();
        jpUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnAgregarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnVolverUsuarios = new javax.swing.JButton();

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(this::itemAbrirActionPerformed);
        popupArchivos.add(itemAbrir);

        itemRenombrar.setText("Renombrar");
        itemRenombrar.addActionListener(this::itemRenombrarActionPerformed);
        popupArchivos.add(itemRenombrar);

        itemEliminar.setText("Eliminar");
        itemEliminar.addActionListener(this::itemEliminarActionPerformed);
        popupArchivos.add(itemEliminar);

        dialogUsuario.setPreferredSize(new java.awt.Dimension(402, 370));

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contrasena:");

        jLabel4.setText("Tipo:");

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Invitado" }));

        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarUsuarioMouseClicked(evt);
            }
        });

        btnCancelarUsuario.setText("Cancelar");
        btnCancelarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialogUsuarioLayout = new javax.swing.GroupLayout(dialogUsuario.getContentPane());
        dialogUsuario.getContentPane().setLayout(dialogUsuarioLayout);
        dialogUsuarioLayout.setHorizontalGroup(
            dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUsuarioLayout.createSequentialGroup()
                .addGroup(dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogUsuarioLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContrasenaCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuarioCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(166, 166, 166))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogUsuarioLayout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addGroup(dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogUsuarioLayout.createSequentialGroup()
                        .addComponent(btnGuardarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarUsuario)
                        .addGap(113, 113, 113))))
        );
        dialogUsuarioLayout.setVerticalGroup(
            dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtUsuarioCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtContrasenaCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarUsuario)
                    .addComponent(btnGuardarUsuario))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpContenedor.setBackground(new java.awt.Color(153, 204, 255));
        jpContenedor.setPreferredSize(new java.awt.Dimension(1000, 650));

        jpLogin.setPreferredSize(new java.awt.Dimension(1000, 650));

        lblTitulo.setForeground(null);
        lblTitulo.setText("CACHOLA OS");

        lblUsuario.setForeground(null);
        lblUsuario.setText("Usuario");

        txtUsuario.setForeground(null);

        lblContrasena.setForeground(null);
        lblContrasena.setText("Contrasena");

        txtContrasena.setForeground(null);

        btnIngresar.setForeground(null);
        btnIngresar.setText("Ingresar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });

        pbLogin.setForeground(null);

        lblEstado.setForeground(null);
        lblEstado.setText("Ingrese sus credenciales");

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(0, 340, Short.MAX_VALUE)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(457, 457, 457))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(btnIngresar)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addGap(156, 156, 156))
                            .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                                .addComponent(lblContrasena)
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addGap(105, 105, 105)))
                        .addGap(315, 315, 315))))
        );
        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(44, 44, 44)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasena)
                .addGap(18, 18, 18)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addGap(47, 47, 47)
                .addComponent(pbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jpInicio.setPreferredSize(new java.awt.Dimension(1000, 650));

        jpNavbar.setBackground(new java.awt.Color(51, 51, 51));
        jpNavbar.setPreferredSize(new java.awt.Dimension(1000, 75));

        lblNombreSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreSistema.setText("CacholaOS");

        btnInicio.setText("Inicio");

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        btnPersonalizar.setText("Personalizar");

        lblUsuarioActual.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioActual.setText("Usuario");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpNavbarLayout = new javax.swing.GroupLayout(jpNavbar);
        jpNavbar.setLayout(jpNavbarLayout);
        jpNavbarLayout.setHorizontalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreSistema)
                .addGap(113, 113, 113)
                .addComponent(btnInicio)
                .addGap(80, 80, 80)
                .addComponent(btnUsuarios)
                .addGap(84, 84, 84)
                .addComponent(btnPersonalizar)
                .addGap(64, 64, 64)
                .addComponent(lblUsuarioActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(45, 45, 45))
        );
        jpNavbarLayout.setVerticalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreSistema)
                    .addComponent(btnInicio)
                    .addComponent(btnUsuarios)
                    .addComponent(btnPersonalizar)
                    .addComponent(lblUsuarioActual)
                    .addComponent(btnCerrarSesion))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpEscritorio.setBackground(new java.awt.Color(51, 51, 51));
        jpEscritorio.setPreferredSize(new java.awt.Dimension(1000, 575));

        btnEditor.setText("Editor de texto");
        btnEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditorMouseClicked(evt);
            }
        });

        btnExplorador.setText("Explorador de Archivos");
        btnExplorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExploradorMouseClicked(evt);
            }
        });

        btnConfiguracion.setText("Configuración");

        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("Hora");

        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha");

        javax.swing.GroupLayout jpEscritorioLayout = new javax.swing.GroupLayout(jpEscritorio);
        jpEscritorio.setLayout(jpEscritorioLayout);
        jpEscritorioLayout.setHorizontalGroup(
            jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExplorador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(789, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(lblHora))
                .addGap(96, 96, 96))
        );
        jpEscritorioLayout.setVerticalGroup(
            jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnExplorador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(139, 139, 139))
        );

        javax.swing.GroupLayout jpInicioLayout = new javax.swing.GroupLayout(jpInicio);
        jpInicio.setLayout(jpInicioLayout);
        jpInicioLayout.setHorizontalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addGroup(jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpNavbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpInicioLayout.setVerticalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addComponent(jpNavbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpEditor.setPreferredSize(new java.awt.Dimension(1000, 650));

        lblTituloEditor.setText("Editor de Texto");

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });

        btnAbrir.setText("Abrir");
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnColorEditor.setText("Color Fondo");
        btnColorEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorEditorMouseClicked(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        txtAreaEditor.setColumns(20);
        txtAreaEditor.setRows(5);
        jScrollPane1.setViewportView(txtAreaEditor);

        btnColorFuente.setText("Color Fuente");
        btnColorFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseClicked(evt);
            }
        });

        lblFuenteEditor.setText("Fuente:");

        jcbFuenteEditor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Times New Roman", "Courier New" }));
        jcbFuenteEditor.addActionListener(this::jcbFuenteEditorActionPerformed);

        lblTamanoEditor.setText("Tamano:");

        jcbTamanoEditor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "24", "28", "32" }));
        jcbTamanoEditor.addActionListener(this::jcbTamanoEditorActionPerformed);

        btnBold.setText("B");
        btnBold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBoldMouseClicked(evt);
            }
        });

        btnItalics.setText("I");
        btnItalics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnItalicsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpEditorLayout = new javax.swing.GroupLayout(jpEditor);
        jpEditor.setLayout(jpEditorLayout);
        jpEditorLayout.setHorizontalGroup(
            jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(lblTituloEditor)
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jpEditorLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEditorLayout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(68, 68, 68)
                                .addComponent(btnAbrir)
                                .addGap(61, 61, 61)
                                .addComponent(btnGuardar))
                            .addGroup(jpEditorLayout.createSequentialGroup()
                                .addComponent(lblFuenteEditor)
                                .addGap(18, 18, 18)
                                .addComponent(jcbFuenteEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lblTamanoEditor)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTamanoEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEditorLayout.createSequentialGroup()
                                .addComponent(btnColorEditor)
                                .addGap(52, 52, 52)
                                .addComponent(btnColorFuente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver))
                            .addGroup(jpEditorLayout.createSequentialGroup()
                                .addComponent(btnBold)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnItalics)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jpEditorLayout.setVerticalGroup(
            jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTituloEditor)
                .addGap(18, 18, 18)
                .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnAbrir)
                    .addComponent(btnGuardar)
                    .addComponent(btnColorEditor)
                    .addComponent(btnVolver)
                    .addComponent(btnColorFuente))
                .addGap(18, 18, 18)
                .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuenteEditor)
                    .addComponent(jcbFuenteEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanoEditor)
                    .addComponent(jcbTamanoEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBold)
                    .addComponent(btnItalics))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jpExplorador.setPreferredSize(new java.awt.Dimension(1000, 650));

        lblExploradorTitulo.setText("Explorador de Archivos");

        treeArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeArchivosMouseClicked(evt);
            }
        });
        treeArchivos.addTreeSelectionListener(this::treeArchivosValueChanged);
        jScrollPane2.setViewportView(treeArchivos);

        tblArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Tamaño", "Ruta"
            }
        ));
        jScrollPane3.setViewportView(tblArchivos);

        btnCrearArchivo.setText("Crear Archivo");
        btnCrearArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearArchivoMouseClicked(evt);
            }
        });

        btnCrearCarpeta.setText("Crear Carpeta");
        btnCrearCarpeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCarpetaMouseClicked(evt);
            }
        });

        btnEliminarArchivo.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarArchivo.setText("Eliminar");
        btnEliminarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarArchivoMouseClicked(evt);
            }
        });

        btnVolverExplorador.setBackground(new java.awt.Color(255, 0, 0));
        btnVolverExplorador.setText("Volver");
        btnVolverExplorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverExploradorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpExploradorLayout = new javax.swing.GroupLayout(jpExplorador);
        jpExplorador.setLayout(jpExploradorLayout);
        jpExploradorLayout.setHorizontalGroup(
            jpExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExploradorLayout.createSequentialGroup()
                .addGroup(jpExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpExploradorLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(lblExploradorTitulo))
                    .addGroup(jpExploradorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jpExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolverExplorador)
                            .addGroup(jpExploradorLayout.createSequentialGroup()
                                .addComponent(btnCrearArchivo)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearCarpeta)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarArchivo)
                                .addGap(600, 600, 600))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpExploradorLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpExploradorLayout.setVerticalGroup(
            jpExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExploradorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblExploradorTitulo)
                .addGap(12, 12, 12)
                .addComponent(btnVolverExplorador)
                .addGap(18, 18, 18)
                .addGroup(jpExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(jpExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearArchivo)
                    .addComponent(btnCrearCarpeta)
                    .addComponent(btnEliminarArchivo))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jpUsuarios.setPreferredSize(new java.awt.Dimension(1000, 650));

        jLabel1.setText("Administracion de Usuarios");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Contrasena", "Tipo"
            }
        ));
        jScrollPane4.setViewportView(tblUsuarios);

        btnAgregarUsuario.setText("Agregar");
        btnAgregarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarUsuarioMouseClicked(evt);
            }
        });

        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseClicked(evt);
            }
        });

        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
        });

        btnVolverUsuarios.setText("Volver");
        btnVolverUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpUsuariosLayout = new javax.swing.GroupLayout(jpUsuarios);
        jpUsuarios.setLayout(jpUsuariosLayout);
        jpUsuariosLayout.setHorizontalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(304, 304, 304)
                .addComponent(btnVolverUsuarios)
                .addGap(47, 47, 47))
        );
        jpUsuariosLayout.setVerticalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVolverUsuarios))
                .addGap(18, 18, 18)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpUsuariosLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAgregarUsuario)
                        .addGap(78, 78, 78)
                        .addComponent(btnEditarUsuario)
                        .addGap(89, 89, 89)
                        .addComponent(btnEliminarUsuario)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addComponent(jpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addComponent(jpEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpExplorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addComponent(jpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addComponent(jpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addComponent(jpEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpExplorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpContenedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        // TODO add your handling code here:
        String nombre = txtUsuario.getText().trim();
        String contrasena = new String(txtContrasena.getPassword());

        if (nombre.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese usuario y contrasena");
            return;
        }//fin del if

        Usuario encontrado = null;

        for (int i = 0; i < cantidadUsuarios; i++) {
            if (usuarios[i].getNombre().equals(nombre) && usuarios[i].getContrasena().equals(contrasena)) {
                encontrado = usuarios[i];
                break;
            }//fin del if
        }//fin del for

        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "Usuario o contrasena incorrecta");

            txtContrasena.setText("");
            return;
        }//fin del if
        Usuario usuarioIngresado = encontrado;

        pbLogin.setValue(0);
        lblEstado.setText("Iniciando sesión...");

        Timer carga = new Timer(50, null);

        carga.addActionListener(e -> {
            int valor = pbLogin.getValue();

            if (valor < 100) {
                pbLogin.setValue(valor + 5);
            } else {
                carga.stop();

                lblEstado.setText("Bienvenido " + usuarioIngresado.getNombre());
                lblUsuarioActual.setText(usuarioIngresado.getNombre());
                
                usuarioActual = usuarioIngresado;

                JOptionPane.showMessageDialog(this,
                        "Bienvenido al sistema " + usuarioIngresado.getNombre());

                jpLogin.setVisible(false);
                jpInicio.setVisible(true);
            }
        });

        carga.start();
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        pbLogin.setValue(0);
        lblEstado.setText("Cerrando sesión...");

        jpInicio.setVisible(false);
        jpLogin.setVisible(true);

        Timer carga = new Timer(50, null);

        carga.addActionListener(e -> {
            int valor = pbLogin.getValue();

            if (valor < 100) {
                pbLogin.setValue(valor + 5);
            } else {
                carga.stop();

                txtUsuario.setText("");
                txtContrasena.setText("");
                lblEstado.setText("Sesión cerrada");
                usuarioActual = null;

                JOptionPane.showMessageDialog(this, "Sesión cerrada correctamente");

                pbLogin.setValue(0);
            }
        });

        carga.start();

    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnEditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorMouseClicked
        // TODO add your handling code here:
        jpInicio.setVisible(false);
        jpEditor.setVisible(true);


    }//GEN-LAST:event_btnEditorMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        jpEditor.setVisible(false);
        jpInicio.setVisible(true);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        // TODO add your handling code here:
        txtAreaEditor.setText("");
        archivoAbierto = null;

        txtAreaEditor.setBackground(Color.WHITE);
        txtAreaEditor.setForeground(Color.BLACK);

        txtAreaEditor.setFont(
                new Font("Arial", Font.PLAIN, 12)
        );

        jcbFuenteEditor.setSelectedItem("Arial");
        jcbTamanoEditor.setSelectedItem("12");

    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();

        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");

        selector.setFileFilter(filtro);

        int opcion = selector.showOpenDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            try {
                BufferedReader lector = new BufferedReader(new FileReader(archivo));

                txtAreaEditor.setText("");

                String linea;

                while ((linea = lector.readLine()) != null) {
                    txtAreaEditor.append(linea + "\n");
                }

                lector.close();
                cargarFormato(archivo);
                archivoAbierto = archivo;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo abrir el archivo");
            }
        }
    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        if (archivoAbierto != null) {

            try {
                FileWriter escritor = new FileWriter(archivoAbierto);

                escritor.write(txtAreaEditor.getText());
                escritor.close();
                guardarFormato(archivoAbierto);

                JOptionPane.showMessageDialog(this,
                        "Cambios guardados correctamente");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo guardar el archivo");
            }

        } else {

            JFileChooser selector = new JFileChooser();

            FileNameExtensionFilter filtro
                    = new FileNameExtensionFilter(
                            "Archivos de texto (*.txt)", "txt"
                    );

            selector.setFileFilter(filtro);

            int opcion = selector.showSaveDialog(this);

            if (opcion == JFileChooser.APPROVE_OPTION) {

                File archivo = selector.getSelectedFile();

                String ruta = archivo.getAbsolutePath();

                if (!ruta.endsWith(".txt")) {
                    archivo = new File(ruta + ".txt");
                }

                try {
                    FileWriter escritor = new FileWriter(archivo);

                    escritor.write(txtAreaEditor.getText());
                    escritor.close();

                    archivoAbierto = archivo;
                    guardarFormato(archivoAbierto);

                    JOptionPane.showMessageDialog(this,
                            "Archivo guardado correctamente");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo guardar el archivo");
                }
            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnColorEditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorEditorMouseClicked
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(
                this,
                "Seleccione un color",
                txtAreaEditor.getBackground()
        );

        if (color != null) {
            txtAreaEditor.setBackground(color);
        }
    }//GEN-LAST:event_btnColorEditorMouseClicked

    private void btnColorFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseClicked
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(
                this,
                "Seleccione el color de la fuente",
                txtAreaEditor.getForeground()
        );

        if (color != null) {
            txtAreaEditor.setForeground(color);
        }
    }//GEN-LAST:event_btnColorFuenteMouseClicked

    private void jcbFuenteEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFuenteEditorActionPerformed
        // TODO add your handling code here:
        String fuente = jcbFuenteEditor.getSelectedItem().toString();

        Font fuenteActual = txtAreaEditor.getFont();

        txtAreaEditor.setFont(
                new Font(fuente, fuenteActual.getStyle(), fuenteActual.getSize())
        );
    }//GEN-LAST:event_jcbFuenteEditorActionPerformed

    private void jcbTamanoEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTamanoEditorActionPerformed
        // TODO add your handling code here:
        int posicion = jcbTamanoEditor.getSelectedIndex();

        int[] tamanos = {12, 14, 16, 18, 20, 24, 28, 32};

        int tamano = tamanos[posicion];

        Font fuenteActual = txtAreaEditor.getFont();

        txtAreaEditor.setFont(
                new Font(fuenteActual.getName(), fuenteActual.getStyle(), tamano)
        );
    }//GEN-LAST:event_jcbTamanoEditorActionPerformed

    private void btnBoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoldMouseClicked
        // TODO add your handling code here:
        Font fuenteActual = txtAreaEditor.getFont();

        if (fuenteActual.isBold()) {
            txtAreaEditor.setFont(
                    fuenteActual.deriveFont(fuenteActual.getStyle() & ~Font.BOLD)
            );
        } else {
            txtAreaEditor.setFont(
                    fuenteActual.deriveFont(fuenteActual.getStyle() | Font.BOLD)
            );
        }
    }//GEN-LAST:event_btnBoldMouseClicked

    private void btnItalicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItalicsMouseClicked
        // TODO add your handling code here:
        Font fuenteActual = txtAreaEditor.getFont();

        if (fuenteActual.isItalic()) {
            txtAreaEditor.setFont(
                    fuenteActual.deriveFont(fuenteActual.getStyle() & ~Font.ITALIC)
            );
        } else {
            txtAreaEditor.setFont(
                    fuenteActual.deriveFont(fuenteActual.getStyle() | Font.ITALIC)
            );
        }
    }//GEN-LAST:event_btnItalicsMouseClicked

    private void btnExploradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExploradorMouseClicked
        // TODO add your handling code here:
        jpInicio.setVisible(false);
        jpExplorador.setVisible(true);
    }//GEN-LAST:event_btnExploradorMouseClicked

    private void btnVolverExploradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverExploradorMouseClicked
        // TODO add your handling code here:
        jpExplorador.setVisible(false);
        jpInicio.setVisible(true);
    }//GEN-LAST:event_btnVolverExploradorMouseClicked

    private void btnCrearCarpetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCarpetaMouseClicked
        // TODO add your handling code here:
        DefaultMutableTreeNode seleccionado = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una carpeta");
            return;
        }

        String nombre = JOptionPane.showInputDialog(this, "Nombre de la nueva carpeta:");

        if (nombre == null || nombre.trim().isEmpty()) {
            return;
        }

        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        Object[] partesRuta = rutaSeleccionada.getPath();

        File carpetaSeleccionada = carpetaPrincipal;

        for (int i = 1; i < partesRuta.length; i++) {
            carpetaSeleccionada = new File(
                    carpetaSeleccionada,
                    partesRuta[i].toString()
            );
        }

        File carpeta = new File(carpetaSeleccionada, nombre);

        if (carpeta.exists()) {
            JOptionPane.showMessageDialog(this, "Ya existe una carpeta con ese nombre");
            return;
        }

        if (carpeta.mkdir()) {

            DefaultMutableTreeNode nuevaCarpeta = new DefaultMutableTreeNode(nombre);

            seleccionado.add(nuevaCarpeta);

            DefaultTreeModel modelo = (DefaultTreeModel) treeArchivos.getModel();

            modelo.reload(seleccionado);

            actualizarTabla(carpetaSeleccionada);

            JOptionPane.showMessageDialog(this, "Carpeta creada correctamente");

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la carpeta");
        }
    }//GEN-LAST:event_btnCrearCarpetaMouseClicked

    private void btnCrearArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearArchivoMouseClicked
        // TODO add your handling code here:
        DefaultMutableTreeNode seleccionado
                = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una carpeta");
            return;
        }

        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        Object[] partesRuta = rutaSeleccionada.getPath();

        File carpetaSeleccionada = carpetaPrincipal;

        for (int i = 1; i < partesRuta.length; i++) {
            carpetaSeleccionada = new File(
                    carpetaSeleccionada,
                    partesRuta[i].toString()
            );
        }

        if (!carpetaSeleccionada.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carpeta");
            return;
        }

        String nombre = JOptionPane.showInputDialog(
                this,
                "Nombre del nuevo archivo:"
        );

        if (nombre == null || nombre.trim().isEmpty()) {
            return;
        }

        if (!nombre.endsWith(".txt")) {
            nombre = nombre + ".txt";
        }

        File archivo = new File(carpetaSeleccionada, nombre);

        if (archivo.exists()) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe un archivo con ese nombre");
            return;
        }

        try {

            if (archivo.createNewFile()) {

                DefaultMutableTreeNode nuevoArchivo
                        = new DefaultMutableTreeNode(nombre);

                seleccionado.add(nuevoArchivo);

                DefaultTreeModel modelo
                        = (DefaultTreeModel) treeArchivos.getModel();

                modelo.reload(seleccionado);

                actualizarTabla(carpetaSeleccionada);

                JOptionPane.showMessageDialog(this,
                        "Archivo creado correctamente");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo crear el archivo");
        }
    }//GEN-LAST:event_btnCrearArchivoMouseClicked

    private void treeArchivosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeArchivosValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode seleccionado
                = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();

        if (seleccionado == null) {
            return;
        }

        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        Object[] partesRuta = rutaSeleccionada.getPath();

        File carpetaSeleccionada = carpetaPrincipal;

        for (int i = 1; i < partesRuta.length; i++) {
            carpetaSeleccionada = new File(
                    carpetaSeleccionada,
                    partesRuta[i].toString()
            );
        }

        DefaultTableModel modelo
                = (DefaultTableModel) tblArchivos.getModel();

        modelo.setRowCount(0);

        if (!carpetaSeleccionada.isDirectory()) {
            return;
        }

        File[] archivos = carpetaSeleccionada.listFiles();

        if (archivos == null) {
            return;
        }

        for (int i = 0; i < archivos.length; i++) {

            String tipo;

            if (archivos[i].isDirectory()) {
                tipo = "Carpeta";
            } else {
                tipo = "Archivo";
            }

            Object[] fila = {
                archivos[i].getName(),
                tipo,
                archivos[i].length() + " bytes",
                archivos[i].getAbsolutePath()
            };

            modelo.addRow(fila);
        }
    }//GEN-LAST:event_treeArchivosValueChanged

    private void btnEliminarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarArchivoMouseClicked
        // TODO add your handling code here:
        DefaultMutableTreeNode seleccionado
                = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un archivo o carpeta");
            return;
        }

        if (seleccionado.isRoot()) {
            JOptionPane.showMessageDialog(this,
                    "No puede eliminar CacholaOS");
            return;
        }

        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        Object[] partesRuta = rutaSeleccionada.getPath();

        File archivoSeleccionado = carpetaPrincipal;

        File carpetaPadre = archivoSeleccionado.getParentFile();

        for (int i = 1; i < partesRuta.length; i++) {
            archivoSeleccionado = new File(
                    archivoSeleccionado,
                    partesRuta[i].toString()
            );
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar " + archivoSeleccionado.getName() + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }
        
        File archivoFormato = null;

        if (archivoSeleccionado.isFile()
                && archivoSeleccionado.getName().endsWith(".txt")) {

            String ruta = archivoSeleccionado.getAbsolutePath();
            ruta = ruta.substring(0, ruta.length() - 4);

            archivoFormato = new File(ruta + ".dat");
        }

        if (archivoSeleccionado.delete()) {
            if (archivoFormato != null && archivoFormato.exists()) {
                archivoFormato.delete();
}

            DefaultTreeModel modelo
                    = (DefaultTreeModel) treeArchivos.getModel();

            modelo.removeNodeFromParent(seleccionado);

            actualizarTabla(carpetaPadre);

            JOptionPane.showMessageDialog(this,
                    "Eliminado correctamente");

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar. Si es una carpeta, debe estar vacía.");
        }
    }//GEN-LAST:event_btnEliminarArchivoMouseClicked

    private void treeArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeArchivosMouseClicked
        // TODO add your handling code here:
        int fila = treeArchivos.getRowForLocation(
                evt.getX(),
                evt.getY()
        );

        if (fila == -1) {
            return;
        }

        treeArchivos.setSelectionRow(fila);

        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            popupArchivos.show(
                    treeArchivos,
                    evt.getX(),
                    evt.getY()
            );
        }
    }//GEN-LAST:event_treeArchivosMouseClicked

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        if (rutaSeleccionada == null) {
            return;
        }

        Object[] partesRuta = rutaSeleccionada.getPath();

        File archivo = carpetaPrincipal;

        for (int i = 1; i < partesRuta.length; i++) {
            archivo = new File(
                    archivo,
                    partesRuta[i].toString()
            );
        }

        if (archivo.isDirectory()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un archivo de texto"
            );
            return;
        }

        try {

            BufferedReader lector
                    = new BufferedReader(new FileReader(archivo));

            txtAreaEditor.setText("");

            String linea;

            while ((linea = lector.readLine()) != null) {
                txtAreaEditor.append(linea + "\n");
            }

            lector.close();

            archivoAbierto = archivo;
            cargarFormato(archivo);

            jpExplorador.setVisible(false);
            jpEditor.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo abrir el archivo"
            );
        }
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRenombrarActionPerformed
        // TODO add your handling code here:
        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        if (rutaSeleccionada == null) {
            return;
        }

        DefaultMutableTreeNode seleccionado
                = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();

        if (seleccionado.isRoot()) {
            JOptionPane.showMessageDialog(this,
                    "No puede renombrar CacholaOS");
            return;
        }

        Object[] partesRuta = rutaSeleccionada.getPath();

        File archivoActual = carpetaPrincipal;

        for (int i = 1; i < partesRuta.length; i++) {
            archivoActual = new File(
                    archivoActual,
                    partesRuta[i].toString()
            );
        }

        String nuevoNombre = JOptionPane.showInputDialog(
                this,
                "Nuevo nombre:",
                archivoActual.getName()
        );

        if (nuevoNombre == null || nuevoNombre.trim().isEmpty()) {
            return;
        }

        nuevoNombre = nuevoNombre.trim();


        if (archivoActual.isFile()
                && archivoActual.getName().endsWith(".txt")
                && !nuevoNombre.endsWith(".txt")) {

            nuevoNombre = nuevoNombre + ".txt";
        }

        File nuevoArchivo = new File(
                archivoActual.getParentFile(),
                nuevoNombre
        );

        if (nuevoArchivo.exists()) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe un archivo o carpeta con ese nombre");
            return;
        }


        File formatoActual = null;
        File formatoNuevo = null;

        if (archivoActual.isFile()
                && archivoActual.getName().endsWith(".txt")) {

            String nombreActualSinTxt
                    = archivoActual.getName().substring(
                            0,
                            archivoActual.getName().length() - 4
                    );

            String nombreNuevoSinTxt
                    = nuevoNombre.substring(
                            0,
                            nuevoNombre.length() - 4
                    );

            formatoActual = new File(
                    archivoActual.getParentFile(),
                    nombreActualSinTxt + ".dat"
            );

            formatoNuevo = new File(
                    archivoActual.getParentFile(),
                    nombreNuevoSinTxt + ".dat"
            );
        }

// Renombrar el .txt o carpeta
        if (archivoActual.renameTo(nuevoArchivo)) {

            // Si existe su .dat, también renombrarlo
            if (formatoActual != null && formatoActual.exists()) {

                if (!formatoActual.renameTo(formatoNuevo)) {
                    JOptionPane.showMessageDialog(this,
                            "El archivo se renombró, pero su formato no pudo renombrarse");
                }
            }

            seleccionado.setUserObject(nuevoNombre);

            DefaultTreeModel modelo
                    = (DefaultTreeModel) treeArchivos.getModel();

            modelo.nodeChanged(seleccionado);

            actualizarTabla(nuevoArchivo.getParentFile());

            JOptionPane.showMessageDialog(this,
                    "Renombrado correctamente");

        } else {

            JOptionPane.showMessageDialog(this,
                    "No se pudo renombrar");
        }
    }//GEN-LAST:event_itemRenombrarActionPerformed

    private void itemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode seleccionado
                = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();

        if (seleccionado == null) {
            return;
        }

        if (seleccionado.isRoot()) {
            JOptionPane.showMessageDialog(this,
                    "No puede eliminar CacholaOS");
            return;
        }

        TreePath rutaSeleccionada = treeArchivos.getSelectionPath();

        Object[] partesRuta = rutaSeleccionada.getPath();

        File archivoSeleccionado = carpetaPrincipal;

        for (int i = 1; i < partesRuta.length; i++) {
            archivoSeleccionado = new File(
                    archivoSeleccionado,
                    partesRuta[i].toString()
            );
        }

        File carpetaPadre = archivoSeleccionado.getParentFile();

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar "
                + archivoSeleccionado.getName() + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }
        File archivoFormato = null;

        if (archivoSeleccionado.isFile()
                && archivoSeleccionado.getName().endsWith(".txt")) {

            String ruta = archivoSeleccionado.getAbsolutePath();
            ruta = ruta.substring(0, ruta.length() - 4);

            archivoFormato = new File(ruta + ".dat");
        }

        if (archivoSeleccionado.delete()) {
            if (archivoFormato != null && archivoFormato.exists()) {
                archivoFormato.delete();
}

            DefaultTreeModel modelo
                    = (DefaultTreeModel) treeArchivos.getModel();

            modelo.removeNodeFromParent(seleccionado);

            actualizarTabla(carpetaPadre);

            JOptionPane.showMessageDialog(this,
                    "Eliminado correctamente");

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar. Si es una carpeta, debe estar vacía.");
        }
    }//GEN-LAST:event_itemEliminarActionPerformed

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        // TODO add your handling code here:
        if (usuarioActual == null) {
            return;
        }

        if (!usuarioActual.getTipo().equals("Administrador")) {
            JOptionPane.showMessageDialog(this,
                    "Solo los administradores pueden administrar usuarios");
            return;
        }

        actualizarTablaUsuarios();

        jpInicio.setVisible(false);
        jpUsuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnVolverUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverUsuariosMouseClicked
        // TODO add your handling code here:
        jpUsuarios.setVisible(false);
        jpInicio.setVisible(true);
    }//GEN-LAST:event_btnVolverUsuariosMouseClicked

    private void btnAgregarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioMouseClicked
        // TODO add your handling code here:
        usuarioEditando = -1;
        txtUsuarioCRUD.setText("");
        txtContrasenaCRUD.setText("");
        cbTipoUsuario.setSelectedIndex(0);

        dialogUsuario.setTitle("Agregar Usuario");
        dialogUsuario.setSize(400, 300);
        dialogUsuario.setLocationRelativeTo(this);
        dialogUsuario.setModal(true);

        dialogUsuario.setVisible(true);
    }//GEN-LAST:event_btnAgregarUsuarioMouseClicked

    private void btnCancelarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarUsuarioMouseClicked
        // TODO add your handling code here:
        dialogUsuario.setVisible(false);
    }//GEN-LAST:event_btnCancelarUsuarioMouseClicked

    private void btnGuardarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioMouseClicked
        // TODO add your handling code here:
        String nombre = txtUsuarioCRUD.getText().trim();
        String contrasena = txtContrasenaCRUD.getText().trim();
        String tipo = cbTipoUsuario.getSelectedItem().toString();

        if (nombre.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese usuario y contraseña");
            return;
        }

        for (int i = 0; i < cantidadUsuarios; i++) {

            if (usuarios[i].getNombre().equals(nombre)
                    && i != usuarioEditando) {

                JOptionPane.showMessageDialog(this,
                        "Ya existe un usuario con ese nombre");
                return;
            }
        }


        if (usuarioEditando >= 0) {

            usuarios[usuarioEditando].setNombre(nombre);
            usuarios[usuarioEditando].setContrasena(contrasena);
            usuarios[usuarioEditando].setTipo(tipo);

            actualizarTablaUsuarios();

            dialogUsuario.setVisible(false);

            JOptionPane.showMessageDialog(this,
                    "Usuario editado correctamente");

            usuarioEditando = -1;
        }else{

            if (cantidadUsuarios >= usuarios.length) {
                JOptionPane.showMessageDialog(this,
                        "No se pueden agregar más usuarios");
                return;
            }

            usuarios[cantidadUsuarios]
                    = new Usuario(nombre, contrasena, tipo);

            cantidadUsuarios++;

            actualizarTablaUsuarios();

            dialogUsuario.setVisible(false);

            JOptionPane.showMessageDialog(this,
                    "Usuario agregado correctamente");
        }
    }//GEN-LAST:event_btnGuardarUsuarioMouseClicked

    private void btnEditarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseClicked
        // TODO add your handling code here:
        int fila = tblUsuarios.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un usuario");
            return;
        }

        usuarioEditando = fila;

        txtUsuarioCRUD.setText(
                usuarios[fila].getNombre()
        );

        txtContrasenaCRUD.setText(
                usuarios[fila].getContrasena()
        );

        cbTipoUsuario.setSelectedItem(
                usuarios[fila].getTipo()
        );

        dialogUsuario.setTitle("Editar Usuario");
        dialogUsuario.setSize(400, 300);
        dialogUsuario.setLocationRelativeTo(this);
        dialogUsuario.setModal(true);

        dialogUsuario.setVisible(true);
    }//GEN-LAST:event_btnEditarUsuarioMouseClicked

    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseClicked
        // TODO add your handling code here:
        int fila = tblUsuarios.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un usuario");
            return;
        }
        
        if (usuarios[fila] == usuarioActual) {
            JOptionPane.showMessageDialog(this,
                    "No puede eliminar el usuario que está actualmente en sesión");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar al usuario "
                + usuarios[fila].getNombre() + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        for (int i = fila; i < cantidadUsuarios - 1; i++) {
            usuarios[i] = usuarios[i + 1];
        }

        usuarios[cantidadUsuarios - 1] = null;
        cantidadUsuarios--;

        actualizarTablaUsuarios();

        JOptionPane.showMessageDialog(this,
                "Usuario eliminado correctamente");
    }//GEN-LAST:event_btnEliminarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProyectoPrincipal().setVisible(true));
    }

    //metodos
    private void cargarArchivos(File carpeta, DefaultMutableTreeNode nodo) {

        File[] archivos = carpeta.listFiles();

        if (archivos == null) {
            return;
        }

        for (int i = 0; i < archivos.length; i++) {

            if (archivos[i].getName().endsWith(".dat")) {
                continue;
            }

            DefaultMutableTreeNode nuevoNodo
                    = new DefaultMutableTreeNode(archivos[i].getName());

            nodo.add(nuevoNodo);

            if (archivos[i].isDirectory()) {
                cargarArchivos(archivos[i], nuevoNodo);
            }
        }
    }

    private void actualizarTabla(File carpeta) {

        DefaultTableModel modelo
                = (DefaultTableModel) tblArchivos.getModel();

        modelo.setRowCount(0);

        if (carpeta == null || !carpeta.isDirectory()) {
            return;
        }

        File[] archivos = carpeta.listFiles();

        if (archivos == null) {
            return;
        }

        for (int i = 0; i < archivos.length; i++) {
            if (archivos[i].getName().endsWith(".dat")) {
                continue;
            }

            String tipo;

            if (archivos[i].isDirectory()) {
                tipo = "Carpeta";
            } else {
                tipo = "Archivo";
            }

            Object[] fila = {
                archivos[i].getName(),
                tipo,
                archivos[i].length() + " bytes",
                archivos[i].getAbsolutePath()
            };

            modelo.addRow(fila);
        }
    }

    private void guardarFormato(File archivo) {

        try {
            String ruta = archivo.getAbsolutePath();

            if (ruta.endsWith(".txt")) {
                ruta = ruta.substring(0, ruta.length() - 4);
            }

            File archivoFormato = new File(ruta + ".dat");

            DataOutputStream salida = new DataOutputStream(new FileOutputStream(archivoFormato));

            Font fuente = txtAreaEditor.getFont();

            salida.writeUTF(fuente.getName());
            salida.writeInt(fuente.getSize());
            salida.writeInt(fuente.getStyle());

            salida.writeInt(txtAreaEditor.getForeground().getRGB());
            salida.writeInt(txtAreaEditor.getBackground().getRGB());

            salida.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo guardar el formato");
        }
    }

    private void cargarFormato(File archivo) {

        try {
            String ruta = archivo.getAbsolutePath();

            if (ruta.endsWith(".txt")) {
                ruta = ruta.substring(0, ruta.length() - 4);
            }

            File archivoFormato = new File(ruta + ".dat");

            if (!archivoFormato.exists()) {
                return;
            }

            DataInputStream entrada = new DataInputStream(new FileInputStream(archivoFormato));

            String nombreFuente = entrada.readUTF();
            int tamanoFuente = entrada.readInt();
            int estiloFuente = entrada.readInt();

            int colorFuente = entrada.readInt();
            int colorFondo = entrada.readInt();

            entrada.close();

            txtAreaEditor.setFont(
                    new Font(nombreFuente, estiloFuente, tamanoFuente)
            );

            txtAreaEditor.setForeground(
                    new Color(colorFuente)
            );

            txtAreaEditor.setBackground(
                    new Color(colorFondo)
            );

            jcbFuenteEditor.setSelectedItem(nombreFuente);
            jcbTamanoEditor.setSelectedItem(
                    String.valueOf(tamanoFuente)
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo cargar el formato");
        }
    }
    
    private void actualizarTablaUsuarios() {

        DefaultTableModel modelo
                = (DefaultTableModel) tblUsuarios.getModel();

        modelo.setRowCount(0);

        for (int i = 0; i < cantidadUsuarios; i++) {

            Object[] fila = {
                usuarios[i].getNombre(),
                usuarios[i].getContrasena(),
                usuarios[i].getTipo()
            };

            modelo.addRow(fila);
        }
    }
    
    private void guardarUsuarios() {

        try {

            ObjectOutputStream salida
                    = new ObjectOutputStream(
                            new FileOutputStream("usuarios.dat")
                    );

            salida.writeInt(cantidadUsuarios);

            for (int i = 0; i < cantidadUsuarios; i++) {
                salida.writeObject(usuarios[i]);
            }

            salida.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudieron guardar los usuarios");
        }
    }
    
    private void cargarUsuarios() {

    File archivoUsuarios = new File("usuarios.dat");

    if (!archivoUsuarios.exists()) {

            usuarios[0]
                    = new Usuario("admin", "1234", "Administrador");

            cantidadUsuarios = 1;

            guardarUsuarios();

            return;
        }

        try {

            ObjectInputStream entrada
                    = new ObjectInputStream(
                            new FileInputStream(archivoUsuarios)
                    );

            cantidadUsuarios = entrada.readInt();

            for (int i = 0; i < cantidadUsuarios; i++) {
                usuarios[i] = (Usuario) entrada.readObject();
            }

            entrada.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudieron cargar los usuarios");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnBold;
    private javax.swing.JButton btnCancelarUsuario;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnColorEditor;
    private javax.swing.JButton btnColorFuente;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnCrearArchivo;
    private javax.swing.JButton btnCrearCarpeta;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEditor;
    private javax.swing.JButton btnEliminarArchivo;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnExplorador;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnItalics;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPersonalizar;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolverExplorador;
    private javax.swing.JButton btnVolverUsuarios;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JDialog dialogUsuario;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemEliminar;
    private javax.swing.JMenuItem itemRenombrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jcbFuenteEditor;
    private javax.swing.JComboBox<String> jcbTamanoEditor;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpEditor;
    private javax.swing.JPanel jpEscritorio;
    private javax.swing.JPanel jpExplorador;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpNavbar;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblExploradorTitulo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFuenteEditor;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreSistema;
    private javax.swing.JLabel lblTamanoEditor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloEditor;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JProgressBar pbLogin;
    private javax.swing.JPopupMenu popupArchivos;
    private javax.swing.JTable tblArchivos;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTree treeArchivos;
    private javax.swing.JTextArea txtAreaEditor;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtContrasenaCRUD;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioCRUD;
    // End of variables declaration//GEN-END:variables
}
